### ISSUE TITLE
broken html

### ISSUE THREAD

**Issue by vcunat** [APNIC-Labs/draft-kskroll-sentinel#26]
On current master the html is badly rendered in the second paragraph of section 2 &ndash; the list of the two labels appear in a different position inside the paragraph.  Curiously, the txt version is OK, so that makes the problem less significant, but still... does this happen for you as well?  (Using latest xml2rfc-2.9.8 ATM.)

**Comment by wkumari** [comment]
Thank you. 

This seemed to have been caused by the <list> element not being on it's own line. Fixed!

**Comment by vcunat** [comment]
Eww, I'd expect some validation to barf if wrong, but great that it's fixed :-)
